### PR TITLE
Post TestFlight fixes

### LINKED ISSUE #290: [WalletConnect] When connecting second time to the same dApp we should quit the previous session
@VDAODAO reported:

> When I connect twice to the same dapp over some time distance, it puts it twice in the (very nice) list of connected dapps

### LINKED ISSUE #311: French encryption declaration approval form
To make our app available in France, we need to:
- ~~figure out how to create a "French encryption declaration approval form".~~
- ~~upload it on Apple Store~~

Here's some more info about it: https://gist.github.com/chrisballinger/7239932

The form is probably this one, but I am not sure: https://www.ssi.gouv.fr/uploads/2015/03/ANNEXE-I.pdf

image
image

### LINKED ISSUE #312: Clicking "Use max" does to not consider decimal points of token
image

### PR DESCRIPTION
**Pull request by nop33**
Closes #312
Closes #311
Closes #290

### CODE REVIEW

**Comment by mvaivre** [comment]
Functional testing:

- Send: When trying to select one of my address as the destination address, the bottom modal closes and get open again

_... continuing_

File: src/screens/SendReceive/Send/AssetsScreen/AssetRow.tsx [hunk 1]
```diff
@@ -64,7 +67,19 @@ const AssetRow = ({ asset, style, isLast }: AssetRowProps) => {
...
+    setAmount((prevAmount) => {
+      const amountLength = cleanedAmount.length
+
+      if (amountLength >= 10) {
+        if (amountLength < 20) {
+          setInputFontSize((prevSize) => prevSize + (prevAmount.length - amountLength))
+        }
+      } else {
+        setInputFontSize(23)
+      }
```
Comment (nop33) [inline src/screens/SendReceive/Send/AssetsScreen/AssetRow.tsx:79]: nit: what about this?

```suggestion
      setInputFontSize((prevSize) =>
        amountLength < 10 ? 23 : amountLength < 20 ? prevSize + (prevAmount.length - amountLength) : prevSize
      )
```

File: src/screens/SendReceive/Send/AssetsScreen/AssetRow.tsx [hunk 2]
```diff
@@ -53,9 +53,12 @@ const AssetRow = ({ asset, style, isLast }: AssetRowProps) => {
 
   const [isSelected, setIsSelected] = useState(!!assetAmount)
   const [amount, setAmount] = useState(
-    assetAmount && assetAmount.amount ? toHumanReadableAmount(assetAmount.amount) : ''
+    assetAmount && assetAmount.amount
+      ? toHumanReadableAmount(assetAmount.amount, !assetIsNft ? asset.decimals : undefined)
+      : ''
   )
   const [error, setError] = useState('')
+  const [inputFontSize, setInputFontSize] = useState(23)
```
Comment (nop33) [inline src/screens/SendReceive/Send/AssetsScreen/AssetRow.tsx:61]: Let's move the constant `23` to a variable, since we're reusing it just below.

File: src/screens/SendReceive/Send/AssetsScreen/AssetRow.tsx (hunk 1 above)
Comment (nop33) [reply src/screens/SendReceive/Send/AssetsScreen/AssetRow.tsx:79]: We need to use this logic in every place we use `setAmount` with a user defined value. This is the case when using `handleUseMaxAmountPress` as well.

I'll take care of both of the above in a commit, if you don't mind.

File: src/screens/SendReceive/Send/AssetsScreen/AssetRow.tsx (hunk 2 above)
Comment (nop33) [reply src/screens/SendReceive/Send/AssetsScreen/AssetRow.tsx:61]: I'll take care of that as well, don't worry about it!

File: src/screens/SendReceive/Send/AssetsScreen/AssetRow.tsx (hunk 1 above)
Comment (nop33) [reply src/screens/SendReceive/Send/AssetsScreen/AssetRow.tsx:79]: When going back and forth between the send flow screens after the amounts have been entered, the font size remains the default one (23)

**Review by mvaivre — APPROVED** [review]
