### PR TITLE
Fix splash screen

### LINKED ISSUE #106: Stuck on the landing screen
Clue : putting the app in the background then restoring it allows to pass this step.

### PR DESCRIPTION
**Pull request by nop33**
Closes #106

In this PR I did manly 3 things:
- Got rid of the `useAppStateChange` hook and instead moved its code directly in the `App.tsx` file. I find it less confusing this way to understand what are the "first things" that happen in the app. Similar approach has been followed on the desktop wallet lately.
- Got rid of the `useRestoreNavigationState` hook so that the depedencies of other hooks is clearer. It was not very clear to me that some `useEffects` were being re-executed because the deps of the `useRestoreNavigationState` hook were updated.
- Added a "special" hook that runs only 1 time and executes the same code as the one being executed when the app becomes active. For some reason, the `'change'` event of the `AppState` is not triggered on the first app launch. I chose to disable eslint for the deps of that hook, otherwise it gets executed every time the `lastNavigationState` changes. I did not find an easy alternative solution. I added a TODO to revisit this approach.

### CODE REVIEW

File: src/screens/LoginScreen.tsx [hunk 1]
```diff
@@ -59,19 +58,19 @@ const LoginScreen = ({
         addressesToInitialize = await deriveWalletStoredAddresses(wallet)
 
         dispatch(walletSwitched({ wallet, addressesToInitialize, pin }))
-        restoreNavigationState(true)
+        setNavigationState()
```
Comment (mvaivre) [inline src/screens/LoginScreen.tsx:61]: Nit: what about setting it to `null` explicitly? Or better yet (IMO), make `setNavigationState` accept either a new state as argument (as it is now), OR the string 'initial' to make it clear that we want to reset the state. Or better yet (IMO) 🙃 to use a `resetNavigationState` function?

**Review by mvaivre — COMMENTED** [review]
One tiny comment. 👏

File: src/screens/LoginScreen.tsx (hunk 1 above)
Comment (nop33) [reply src/screens/LoginScreen.tsx:61]: hehe alright, I'll make it more explicit! I agree with you

**Review by mvaivre — APPROVED** [review]
